### ISSUE TITLE
selector overridden by error

### ISSUE THREAD

**Issue by SambacFeng** [activeguild/css-to-vanilla-extract#31]
The same css selector with non-conflicting styles applied, but only the one written at the end is converted correctly during the conversion
![screenshot of using the online app](https://user-images.githubusercontent.com/56753082/184054676-8b3716c2-e65d-4e48-97a4-3c4fad224a7a.png)
styles of L1-L11 doesn‘t appear in the results

**Comment by activeguild** [comment]
@SambacFeng 
Hi!Thanks for the contact.
I'll check the cause of the problem.

**Comment by activeguild** [comment]
@SambacFeng 

I've released the latest version in response.
Please check it out.
https://css-to-vanilla-extract.netlify.app/
