### ISSUE TITLE
Property changed the ordering

### ISSUE THREAD

**Issue by Hmilyxj** [activeguild/css-to-vanilla-extract#33]
I have a suggestion, is it better not to change the order of the properties...
![image](https://user-images.githubusercontent.com/23240516/184538439-f9fac6a1-fe72-41c5-bafe-af30d12e0217.png)

**Comment by activeguild** [comment]
I'll try to make a survey.

**Comment by activeguild** [comment]
@Hmilyxj 
I've released an updated library that maintains the property order.
